server:
  port: 8080

spring:
  application:
    name: subscription_and_user_management_service
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.springframework.security: INFO
